#!/bin/sh
echo "Running ktlint & detekt..."

OUTPUT="result"
./gradlew ktlint detekt --daemon > ${OUTPUT}
EXIT_CODE=$?

if [ ${EXIT_CODE} -ne 0 ]; then
    cat ${OUTPUT}
    rm ${OUTPUT}
    echo "*********************************************"
    echo "            Checks     Failed                "
    echo "    Please fix the tests before pushing      "
    echo "*********************************************"
    exit ${EXIT_CODE}
else
    rm ${OUTPUT}
    echo "*********************************************"
    echo "         Ktlint&detekt succeeded             "
    echo "*********************************************"
fi
